# Form implementation generated from reading ui file 'add_changeWindow_order.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Add_Change_window2(object):
    def setupUi(self, Add_Change_window2):
        Add_Change_window2.setObjectName("Add_Change_window2")
        Add_Change_window2.resize(400, 500)
        Add_Change_window2.setMinimumSize(QtCore.QSize(400, 500))
        Add_Change_window2.setMaximumSize(QtCore.QSize(550, 700))
        Add_Change_window2.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Add_Change_window2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit_id_user_diag = QtWidgets.QTextEdit(parent=Add_Change_window2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_id_user_diag.sizePolicy().hasHeightForWidth())
        self.edit_id_user_diag.setSizePolicy(sizePolicy)
        self.edit_id_user_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_id_user_diag.setFont(font)
        self.edit_id_user_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_id_user_diag.setObjectName("edit_id_user_diag")
        self.verticalLayout.addWidget(self.edit_id_user_diag)
        self.edit_id_service_diag = QtWidgets.QTextEdit(parent=Add_Change_window2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_id_service_diag.sizePolicy().hasHeightForWidth())
        self.edit_id_service_diag.setSizePolicy(sizePolicy)
        self.edit_id_service_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_id_service_diag.setFont(font)
        self.edit_id_service_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_id_service_diag.setObjectName("edit_id_service_diag")
        self.verticalLayout.addWidget(self.edit_id_service_diag)
        self.edit_Mark_diag = QtWidgets.QTextEdit(parent=Add_Change_window2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_Mark_diag.sizePolicy().hasHeightForWidth())
        self.edit_Mark_diag.setSizePolicy(sizePolicy)
        self.edit_Mark_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_Mark_diag.setFont(font)
        self.edit_Mark_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_Mark_diag.setObjectName("edit_Mark_diag")
        self.verticalLayout.addWidget(self.edit_Mark_diag)
        self.edit_Description_diag = QtWidgets.QTextEdit(parent=Add_Change_window2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_Description_diag.sizePolicy().hasHeightForWidth())
        self.edit_Description_diag.setSizePolicy(sizePolicy)
        self.edit_Description_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_Description_diag.setFont(font)
        self.edit_Description_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_Description_diag.setObjectName("edit_Description_diag")
        self.verticalLayout.addWidget(self.edit_Description_diag)
        self.edit_Date_diag = QtWidgets.QTextEdit(parent=Add_Change_window2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_Date_diag.sizePolicy().hasHeightForWidth())
        self.edit_Date_diag.setSizePolicy(sizePolicy)
        self.edit_Date_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_Date_diag.setFont(font)
        self.edit_Date_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_Date_diag.setObjectName("edit_Date_diag")
        self.verticalLayout.addWidget(self.edit_Date_diag)
        self.btn_add_diag = QtWidgets.QPushButton(parent=Add_Change_window2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_diag.sizePolicy().hasHeightForWidth())
        self.btn_add_diag.setSizePolicy(sizePolicy)
        self.btn_add_diag.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.btn_add_diag.setFont(font)
        self.btn_add_diag.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add_diag.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_add_diag.setObjectName("btn_add_diag")
        self.verticalLayout.addWidget(self.btn_add_diag)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Add_Change_window2)
        QtCore.QMetaObject.connectSlotsByName(Add_Change_window2)

    def retranslateUi(self, Add_Change_window2):
        _translate = QtCore.QCoreApplication.translate
        Add_Change_window2.setWindowTitle(_translate("Add_Change_window2", "Dialog"))
        self.edit_id_user_diag.setPlaceholderText(_translate("Add_Change_window2", "id  пользователя"))
        self.edit_id_service_diag.setPlaceholderText(_translate("Add_Change_window2", "id услуги"))
        self.edit_Mark_diag.setPlaceholderText(_translate("Add_Change_window2", "марка машины"))
        self.edit_Description_diag.setPlaceholderText(_translate("Add_Change_window2", "описание проблемы"))
        self.edit_Date_diag.setPlaceholderText(_translate("Add_Change_window2", "дата"))
        self.btn_add_diag.setText(_translate("Add_Change_window2", "добавить"))
