# Form implementation generated from reading ui file 'add_changeWindow_service.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Add_Change_window3(object):
    def setupUi(self, Add_Change_window3):
        Add_Change_window3.setObjectName("Add_Change_window3")
        Add_Change_window3.resize(400, 400)
        Add_Change_window3.setMinimumSize(QtCore.QSize(400, 400))
        Add_Change_window3.setMaximumSize(QtCore.QSize(550, 400))
        Add_Change_window3.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Add_Change_window3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit_name_diag = QtWidgets.QTextEdit(parent=Add_Change_window3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_name_diag.sizePolicy().hasHeightForWidth())
        self.edit_name_diag.setSizePolicy(sizePolicy)
        self.edit_name_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_name_diag.setFont(font)
        self.edit_name_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_name_diag.setObjectName("edit_name_diag")
        self.verticalLayout.addWidget(self.edit_name_diag)
        self.edit_price_diag = QtWidgets.QTextEdit(parent=Add_Change_window3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_price_diag.sizePolicy().hasHeightForWidth())
        self.edit_price_diag.setSizePolicy(sizePolicy)
        self.edit_price_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_price_diag.setFont(font)
        self.edit_price_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_price_diag.setObjectName("edit_price_diag")
        self.verticalLayout.addWidget(self.edit_price_diag)
        self.btn_add_diag = QtWidgets.QPushButton(parent=Add_Change_window3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_diag.sizePolicy().hasHeightForWidth())
        self.btn_add_diag.setSizePolicy(sizePolicy)
        self.btn_add_diag.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.btn_add_diag.setFont(font)
        self.btn_add_diag.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add_diag.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_add_diag.setObjectName("btn_add_diag")
        self.verticalLayout.addWidget(self.btn_add_diag)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Add_Change_window3)
        QtCore.QMetaObject.connectSlotsByName(Add_Change_window3)

    def retranslateUi(self, Add_Change_window3):
        _translate = QtCore.QCoreApplication.translate
        Add_Change_window3.setWindowTitle(_translate("Add_Change_window3", "Dialog"))
        self.edit_name_diag.setPlaceholderText(_translate("Add_Change_window3", "название услуги"))
        self.edit_price_diag.setPlaceholderText(_translate("Add_Change_window3", "цена"))
        self.btn_add_diag.setText(_translate("Add_Change_window3", "добавить"))
