# Form implementation generated from reading ui file 'add_changeWindow_user.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Add_Change_window(object):
    def setupUi(self, Add_Change_window):
        Add_Change_window.setObjectName("Add_Change_window")
        Add_Change_window.resize(400, 500)
        Add_Change_window.setMinimumSize(QtCore.QSize(400, 500))
        Add_Change_window.setMaximumSize(QtCore.QSize(550, 700))
        Add_Change_window.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Add_Change_window)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.edit_Firstname_diag = QtWidgets.QTextEdit(parent=Add_Change_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_Firstname_diag.sizePolicy().hasHeightForWidth())
        self.edit_Firstname_diag.setSizePolicy(sizePolicy)
        self.edit_Firstname_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_Firstname_diag.setFont(font)
        self.edit_Firstname_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_Firstname_diag.setObjectName("edit_Firstname_diag")
        self.verticalLayout.addWidget(self.edit_Firstname_diag)
        self.edit_Lastname_diag = QtWidgets.QTextEdit(parent=Add_Change_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_Lastname_diag.sizePolicy().hasHeightForWidth())
        self.edit_Lastname_diag.setSizePolicy(sizePolicy)
        self.edit_Lastname_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_Lastname_diag.setFont(font)
        self.edit_Lastname_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_Lastname_diag.setObjectName("edit_Lastname_diag")
        self.verticalLayout.addWidget(self.edit_Lastname_diag)
        self.edit_Login_diag = QtWidgets.QTextEdit(parent=Add_Change_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_Login_diag.sizePolicy().hasHeightForWidth())
        self.edit_Login_diag.setSizePolicy(sizePolicy)
        self.edit_Login_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_Login_diag.setFont(font)
        self.edit_Login_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_Login_diag.setObjectName("edit_Login_diag")
        self.verticalLayout.addWidget(self.edit_Login_diag)
        self.edit_Password_diag = QtWidgets.QTextEdit(parent=Add_Change_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_Password_diag.sizePolicy().hasHeightForWidth())
        self.edit_Password_diag.setSizePolicy(sizePolicy)
        self.edit_Password_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_Password_diag.setFont(font)
        self.edit_Password_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_Password_diag.setObjectName("edit_Password_diag")
        self.verticalLayout.addWidget(self.edit_Password_diag)
        self.edit_Age_diag = QtWidgets.QTextEdit(parent=Add_Change_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_Age_diag.sizePolicy().hasHeightForWidth())
        self.edit_Age_diag.setSizePolicy(sizePolicy)
        self.edit_Age_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_Age_diag.setFont(font)
        self.edit_Age_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_Age_diag.setObjectName("edit_Age_diag")
        self.verticalLayout.addWidget(self.edit_Age_diag)
        self.edit_number_phone_diag = QtWidgets.QTextEdit(parent=Add_Change_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_number_phone_diag.sizePolicy().hasHeightForWidth())
        self.edit_number_phone_diag.setSizePolicy(sizePolicy)
        self.edit_number_phone_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_number_phone_diag.setFont(font)
        self.edit_number_phone_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_number_phone_diag.setObjectName("edit_number_phone_diag")
        self.verticalLayout.addWidget(self.edit_number_phone_diag)
        self.edit_Admin_diag = QtWidgets.QTextEdit(parent=Add_Change_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_Admin_diag.sizePolicy().hasHeightForWidth())
        self.edit_Admin_diag.setSizePolicy(sizePolicy)
        self.edit_Admin_diag.setMaximumSize(QtCore.QSize(16777215, 47))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.edit_Admin_diag.setFont(font)
        self.edit_Admin_diag.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"")
        self.edit_Admin_diag.setObjectName("edit_Admin_diag")
        self.verticalLayout.addWidget(self.edit_Admin_diag)
        self.btn_add_diag = QtWidgets.QPushButton(parent=Add_Change_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_diag.sizePolicy().hasHeightForWidth())
        self.btn_add_diag.setSizePolicy(sizePolicy)
        self.btn_add_diag.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.btn_add_diag.setFont(font)
        self.btn_add_diag.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add_diag.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_add_diag.setObjectName("btn_add_diag")
        self.verticalLayout.addWidget(self.btn_add_diag)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Add_Change_window)
        QtCore.QMetaObject.connectSlotsByName(Add_Change_window)

    def retranslateUi(self, Add_Change_window):
        _translate = QtCore.QCoreApplication.translate
        Add_Change_window.setWindowTitle(_translate("Add_Change_window", "Dialog"))
        self.edit_Firstname_diag.setPlaceholderText(_translate("Add_Change_window", "имя"))
        self.edit_Lastname_diag.setPlaceholderText(_translate("Add_Change_window", "фамилия"))
        self.edit_Login_diag.setPlaceholderText(_translate("Add_Change_window", "логин"))
        self.edit_Password_diag.setPlaceholderText(_translate("Add_Change_window", "пароль"))
        self.edit_Age_diag.setPlaceholderText(_translate("Add_Change_window", "возраст"))
        self.edit_number_phone_diag.setPlaceholderText(_translate("Add_Change_window", "номер телефона"))
        self.edit_Admin_diag.setPlaceholderText(_translate("Add_Change_window", "админ"))
        self.btn_add_diag.setText(_translate("Add_Change_window", "добавить"))
