# Form implementation generated from reading ui file 'AdminWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(1100, 800)
        AdminWindow.setMinimumSize(QtCore.QSize(1000, 800))
        self.centralwidget = QtWidgets.QWidget(parent=AdminWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Left_Frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.Left_Frame.setMinimumSize(QtCore.QSize(70, 0))
        self.Left_Frame.setMaximumSize(QtCore.QSize(70, 16777215))
        self.Left_Frame.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.Left_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Left_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Left_Frame.setLineWidth(0)
        self.Left_Frame.setObjectName("Left_Frame")
        self.btn_exit_admin = QtWidgets.QPushButton(parent=self.Left_Frame)
        self.btn_exit_admin.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.btn_exit_admin.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_exit_admin.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_exit_admin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_exit_admin.setStyleSheet("QPushButton{\n"
"background-color: rgb(40, 44, 52);\n"
"border: 2px solid rgb(40, 44, 52);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(40, 44, 52); \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}")
        self.btn_exit_admin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./resources/cil-account-logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_exit_admin.setIcon(icon)
        self.btn_exit_admin.setObjectName("btn_exit_admin")
        self.horizontalLayout.addWidget(self.Left_Frame)
        self.Right_Frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.Right_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Right_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Right_Frame.setObjectName("Right_Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Right_Frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Frame = QtWidgets.QFrame(parent=self.Right_Frame)
        self.Top_Frame.setMinimumSize(QtCore.QSize(0, 320))
        self.Top_Frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Top_Frame.setStyleSheet("background-color: rgb(40, 44, 52);\n"
"")
        self.Top_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Top_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Top_Frame.setLineWidth(0)
        self.Top_Frame.setObjectName("Top_Frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Top_Frame)
        self.horizontalLayout_3.setContentsMargins(9, -1, 9, 9)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Left_top_Frame = QtWidgets.QFrame(parent=self.Top_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Left_top_Frame.sizePolicy().hasHeightForWidth())
        self.Left_top_Frame.setSizePolicy(sizePolicy)
        self.Left_top_Frame.setMinimumSize(QtCore.QSize(700, 0))
        self.Left_top_Frame.setMaximumSize(QtCore.QSize(309, 16777215))
        self.Left_top_Frame.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.Left_top_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Left_top_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Left_top_Frame.setObjectName("Left_top_Frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Left_top_Frame)
        self.horizontalLayout_5.setContentsMargins(9, 9, 20, 9)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.graphWidget = PlotWidget(parent=self.Left_top_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphWidget.sizePolicy().hasHeightForWidth())
        self.graphWidget.setSizePolicy(sizePolicy)
        self.graphWidget.setMinimumSize(QtCore.QSize(278, 278))
        self.graphWidget.setMaximumSize(QtCore.QSize(278, 278))
        self.graphWidget.setStyleSheet("")
        self.graphWidget.setObjectName("graphWidget")
        self.horizontalLayout_5.addWidget(self.graphWidget)
        self.Center_top_Frame = QtWidgets.QFrame(parent=self.Left_top_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Center_top_Frame.sizePolicy().hasHeightForWidth())
        self.Center_top_Frame.setSizePolicy(sizePolicy)
        self.Center_top_Frame.setMinimumSize(QtCore.QSize(320, 98))
        self.Center_top_Frame.setMaximumSize(QtCore.QSize(320, 16777215))
        self.Center_top_Frame.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.Center_top_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Center_top_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Center_top_Frame.setObjectName("Center_top_Frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Center_top_Frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dateEdit_admin = QtWidgets.QDateEdit(parent=self.Center_top_Frame)
        self.dateEdit_admin.setMinimumSize(QtCore.QSize(296, 47))
        self.dateEdit_admin.setMaximumSize(QtCore.QSize(296, 47))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateEdit_admin.setFont(font)
        self.dateEdit_admin.setStyleSheet("color: rgb(192, 218, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border: 2px solid rgb(43, 51, 67); \n"
"border-radius: 15px;")
        self.dateEdit_admin.setObjectName("dateEdit_admin")
        self.verticalLayout_2.addWidget(self.dateEdit_admin)
        self.btn_select_date = QtWidgets.QPushButton(parent=self.Center_top_Frame)
        self.btn_select_date.setMinimumSize(QtCore.QSize(296, 47))
        self.btn_select_date.setMaximumSize(QtCore.QSize(296, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_select_date.setFont(font)
        self.btn_select_date.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_select_date.setObjectName("btn_select_date")
        self.verticalLayout_2.addWidget(self.btn_select_date)
        self.horizontalLayout_5.addWidget(self.Center_top_Frame)
        self.horizontalLayout_3.addWidget(self.Left_top_Frame, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Right_top_Frame = QtWidgets.QFrame(parent=self.Top_Frame)
        self.Right_top_Frame.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.Right_top_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Right_top_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Right_top_Frame.setObjectName("Right_top_Frame")
        self.horizontalLayout_3.addWidget(self.Right_top_Frame)
        self.verticalLayout.addWidget(self.Top_Frame)
        self.Bot_Frame = QtWidgets.QFrame(parent=self.Right_Frame)
        self.Bot_Frame.setMinimumSize(QtCore.QSize(300, 0))
        self.Bot_Frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Bot_Frame.setStyleSheet("background-color: rgb(40, 44, 52);\n"
"")
        self.Bot_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Bot_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Bot_Frame.setLineWidth(0)
        self.Bot_Frame.setObjectName("Bot_Frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Bot_Frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.Bot_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"   border: 1px solid gray;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  background-color: rgb(40, 44, 52);\n"
"  color:rgb(192, 218, 255);\n"
"  padding: 10px;\n"
"  border: 2px solid rgb(40, 44, 52);\n"
"  border-radius: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background-color: rgb(43, 51, 67);\n"
" }\n"
"\n"
"QTabWidget::pane { \n"
"   border: none;\n"
"}\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.H_Lay_Btn1 = QtWidgets.QHBoxLayout()
        self.H_Lay_Btn1.setContentsMargins(0, -1, 0, -1)
        self.H_Lay_Btn1.setSpacing(30)
        self.H_Lay_Btn1.setObjectName("H_Lay_Btn1")
        self.btn_add1 = QtWidgets.QPushButton(parent=self.tab_1)
        self.btn_add1.setMinimumSize(QtCore.QSize(296, 35))
        self.btn_add1.setMaximumSize(QtCore.QSize(296, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_add1.setFont(font)
        self.btn_add1.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_add1.setObjectName("btn_add1")
        self.H_Lay_Btn1.addWidget(self.btn_add1)
        self.btn_change1 = QtWidgets.QPushButton(parent=self.tab_1)
        self.btn_change1.setMinimumSize(QtCore.QSize(296, 35))
        self.btn_change1.setMaximumSize(QtCore.QSize(296, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_change1.setFont(font)
        self.btn_change1.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_change1.setObjectName("btn_change1")
        self.H_Lay_Btn1.addWidget(self.btn_change1)
        self.btn_delete1 = QtWidgets.QPushButton(parent=self.tab_1)
        self.btn_delete1.setMinimumSize(QtCore.QSize(296, 35))
        self.btn_delete1.setMaximumSize(QtCore.QSize(296, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_delete1.setFont(font)
        self.btn_delete1.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_delete1.setObjectName("btn_delete1")
        self.H_Lay_Btn1.addWidget(self.btn_delete1, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_3.addLayout(self.H_Lay_Btn1)
        self.tableView_1 = QtWidgets.QTableView(parent=self.tab_1)
        self.tableView_1.setStyleSheet("QTableView {\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-top-right-radius: 7px;\n"
"border-top-left-radius: 7px; \n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"color :rgb(192, 218, 255);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: rgb(33, 37, 43);  \n"
"color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"height: 50px;\n"
"font-size: 16pt;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    border-style: none;\n"
"}\n"
"\n"
"QTableView::item:selected{\n"
"    border: none;\n"
"    color:rgb(192, 218, 255);\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.tableView_1.setShowGrid(True)
        self.tableView_1.setObjectName("tableView_1")
        self.verticalLayout_3.addWidget(self.tableView_1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.H_Lay_Btn1_2 = QtWidgets.QHBoxLayout()
        self.H_Lay_Btn1_2.setContentsMargins(0, -1, 0, -1)
        self.H_Lay_Btn1_2.setSpacing(30)
        self.H_Lay_Btn1_2.setObjectName("H_Lay_Btn1_2")
        self.btn_add2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.btn_add2.setMinimumSize(QtCore.QSize(296, 35))
        self.btn_add2.setMaximumSize(QtCore.QSize(296, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_add2.setFont(font)
        self.btn_add2.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_add2.setObjectName("btn_add2")
        self.H_Lay_Btn1_2.addWidget(self.btn_add2)
        self.btn_change2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.btn_change2.setMinimumSize(QtCore.QSize(296, 35))
        self.btn_change2.setMaximumSize(QtCore.QSize(296, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_change2.setFont(font)
        self.btn_change2.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_change2.setObjectName("btn_change2")
        self.H_Lay_Btn1_2.addWidget(self.btn_change2)
        self.btn_delete2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.btn_delete2.setMinimumSize(QtCore.QSize(296, 35))
        self.btn_delete2.setMaximumSize(QtCore.QSize(296, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_delete2.setFont(font)
        self.btn_delete2.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_delete2.setObjectName("btn_delete2")
        self.H_Lay_Btn1_2.addWidget(self.btn_delete2, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_4.addLayout(self.H_Lay_Btn1_2)
        self.tableView_2 = QtWidgets.QTableView(parent=self.tab_2)
        self.tableView_2.setStyleSheet("QTableView {\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-top-right-radius: 7px;\n"
"border-top-left-radius: 7px; \n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"color :rgb(192, 218, 255);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: rgb(33, 37, 43);  \n"
"color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"height: 50px;\n"
"font-size: 16pt;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    border-style: none;\n"
"}\n"
"\n"
"QTableView::item:selected{\n"
"    border: none;\n"
"    color:rgb(192, 218, 255);\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.tableView_2.setShowGrid(True)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_4.addWidget(self.tableView_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.H_Lay_Btn_3 = QtWidgets.QHBoxLayout()
        self.H_Lay_Btn_3.setContentsMargins(0, -1, 30, -1)
        self.H_Lay_Btn_3.setSpacing(30)
        self.H_Lay_Btn_3.setObjectName("H_Lay_Btn_3")
        self.btn_add3 = QtWidgets.QPushButton(parent=self.tab_3)
        self.btn_add3.setMinimumSize(QtCore.QSize(296, 35))
        self.btn_add3.setMaximumSize(QtCore.QSize(296, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_add3.setFont(font)
        self.btn_add3.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_add3.setObjectName("btn_add3")
        self.H_Lay_Btn_3.addWidget(self.btn_add3)
        self.btn_change3 = QtWidgets.QPushButton(parent=self.tab_3)
        self.btn_change3.setMinimumSize(QtCore.QSize(296, 35))
        self.btn_change3.setMaximumSize(QtCore.QSize(296, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_change3.setFont(font)
        self.btn_change3.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_change3.setObjectName("btn_change3")
        self.H_Lay_Btn_3.addWidget(self.btn_change3)
        self.btn_delete3 = QtWidgets.QPushButton(parent=self.tab_3)
        self.btn_delete3.setMinimumSize(QtCore.QSize(296, 35))
        self.btn_delete3.setMaximumSize(QtCore.QSize(296, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_delete3.setFont(font)
        self.btn_delete3.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_delete3.setObjectName("btn_delete3")
        self.H_Lay_Btn_3.addWidget(self.btn_delete3, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_5.addLayout(self.H_Lay_Btn_3)
        self.tableView_3 = QtWidgets.QTableView(parent=self.tab_3)
        self.tableView_3.setStyleSheet("QTableView {\n"
"background-color: rgba(255, 255, 255, 30); \n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-top-right-radius: 7px;\n"
"border-top-left-radius: 7px; \n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"color :rgb(192, 218, 255);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: rgb(33, 37, 43);  \n"
"color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"height: 50px;\n"
"font-size: 16pt;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    border-style: none;\n"
"}\n"
"\n"
"QTableView::item:selected{\n"
"    border: none;\n"
"    color:rgb(192, 218, 255);\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.tableView_3.setShowGrid(True)
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_5.addWidget(self.tableView_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.Bot_Frame)
        self.horizontalLayout.addWidget(self.Right_Frame)
        AdminWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "MainWindow"))
        self.btn_select_date.setText(_translate("AdminWindow", "Выбрать"))
        self.btn_add1.setText(_translate("AdminWindow", "добавить"))
        self.btn_change1.setText(_translate("AdminWindow", "изменить"))
        self.btn_delete1.setText(_translate("AdminWindow", "удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("AdminWindow", "таблица 1"))
        self.btn_add2.setText(_translate("AdminWindow", "добавить"))
        self.btn_change2.setText(_translate("AdminWindow", "изменить"))
        self.btn_delete2.setText(_translate("AdminWindow", "удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AdminWindow", "таблица 2"))
        self.btn_add3.setText(_translate("AdminWindow", "добавить"))
        self.btn_change3.setText(_translate("AdminWindow", "изменить"))
        self.btn_delete3.setText(_translate("AdminWindow", "удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("AdminWindow", "таблица 3"))
from pyqtgraph import PlotWidget
