# Form implementation generated from reading ui file 'RegistrationWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(850, 700)
        self.centralwidget = QtWidgets.QWidget(parent=RegistrationWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 500))
        self.centralwidget.setStyleSheet("background-color: rgb(40, 44, 52);\n"
"\n"
"font:\"Segoe UI\";\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Left_Frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.Left_Frame.setMinimumSize(QtCore.QSize(70, 0))
        self.Left_Frame.setMaximumSize(QtCore.QSize(70, 16777215))
        self.Left_Frame.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.Left_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Left_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Left_Frame.setLineWidth(0)
        self.Left_Frame.setObjectName("Left_Frame")
        self.btn_exit_reg = QtWidgets.QPushButton(parent=self.Left_Frame)
        self.btn_exit_reg.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.btn_exit_reg.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_exit_reg.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_exit_reg.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_exit_reg.setStyleSheet("QPushButton{\n"
"background-color: rgb(40, 44, 52);\n"
"border: 2px solid rgb(40, 44, 52);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(40, 44, 52); \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}")
        self.btn_exit_reg.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./resources/cil-account-logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_exit_reg.setIcon(icon)
        self.btn_exit_reg.setObjectName("btn_exit_reg")
        self.horizontalLayout.addWidget(self.Left_Frame)
        self.Right_Frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.Right_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Right_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Right_Frame.setObjectName("Right_Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Right_Frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Frame = QtWidgets.QFrame(parent=self.Right_Frame)
        self.Top_Frame.setMinimumSize(QtCore.QSize(0, 320))
        self.Top_Frame.setMaximumSize(QtCore.QSize(16777215, 320))
        self.Top_Frame.setStyleSheet("background-color: rgb(40, 44, 52);\n"
"")
        self.Top_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Top_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Top_Frame.setLineWidth(0)
        self.Top_Frame.setObjectName("Top_Frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Top_Frame)
        self.verticalLayout_2.setContentsMargins(9, 9, -1, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_registration = QtWidgets.QLabel(parent=self.Top_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.label_registration.setFont(font)
        self.label_registration.setStyleSheet("color: rgb(192, 218, 255);")
        self.label_registration.setObjectName("label_registration")
        self.verticalLayout_2.addWidget(self.label_registration, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_icon_man = QtWidgets.QLabel(parent=self.Top_Frame)
        self.label_icon_man.setMaximumSize(QtCore.QSize(300, 300))
        self.label_icon_man.setText("")
        self.label_icon_man.setPixmap(QtGui.QPixmap("./resources/icon_prof.png"))
        self.label_icon_man.setScaledContents(True)
        self.label_icon_man.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_icon_man.setObjectName("label_icon_man")
        self.verticalLayout_2.addWidget(self.label_icon_man, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.Top_Frame)
        self.Bot_Frame = QtWidgets.QFrame(parent=self.Right_Frame)
        self.Bot_Frame.setMinimumSize(QtCore.QSize(300, 0))
        self.Bot_Frame.setStyleSheet("background-color: rgb(40, 44, 52);\n"
"")
        self.Bot_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Bot_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Bot_Frame.setLineWidth(0)
        self.Bot_Frame.setObjectName("Bot_Frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Bot_Frame)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Holow_L_Frame = QtWidgets.QFrame(parent=self.Bot_Frame)
        self.Holow_L_Frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Holow_L_Frame.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.Holow_L_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Holow_L_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Holow_L_Frame.setObjectName("Holow_L_Frame")
        self.horizontalLayout_2.addWidget(self.Holow_L_Frame)
        self.Reg_Frame = QtWidgets.QFrame(parent=self.Bot_Frame)
        self.Reg_Frame.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.Reg_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Reg_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Reg_Frame.setObjectName("Reg_Frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Reg_Frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.edit_login_reg = QtWidgets.QLineEdit(parent=self.Reg_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_login_reg.sizePolicy().hasHeightForWidth())
        self.edit_login_reg.setSizePolicy(sizePolicy)
        self.edit_login_reg.setMinimumSize(QtCore.QSize(400, 50))
        self.edit_login_reg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_login_reg.setFont(font)
        self.edit_login_reg.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;\n"
"\n"
"")
        self.edit_login_reg.setObjectName("edit_login_reg")
        self.verticalLayout_3.addWidget(self.edit_login_reg, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.edit_password_reg = QtWidgets.QLineEdit(parent=self.Reg_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_password_reg.sizePolicy().hasHeightForWidth())
        self.edit_password_reg.setSizePolicy(sizePolicy)
        self.edit_password_reg.setMinimumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_password_reg.setFont(font)
        self.edit_password_reg.setStyleSheet("color: rgb(192, 218, 255);\n"
"border: 2px solid rgb(78, 175, 255);  \n"
"border-radius: 15px;")
        self.edit_password_reg.setObjectName("edit_password_reg")
        self.verticalLayout_3.addWidget(self.edit_password_reg, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.btn_enter_reg = QtWidgets.QPushButton(parent=self.Reg_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_enter_reg.sizePolicy().hasHeightForWidth())
        self.btn_enter_reg.setSizePolicy(sizePolicy)
        self.btn_enter_reg.setMinimumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_enter_reg.setFont(font)
        self.btn_enter_reg.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_enter_reg.setStyleSheet("QPushButton{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.btn_enter_reg.setObjectName("btn_enter_reg")
        self.verticalLayout_3.addWidget(self.btn_enter_reg, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.Reg_Frame)
        self.Holow_R_Frame = QtWidgets.QFrame(parent=self.Bot_Frame)
        self.Holow_R_Frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Holow_R_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Holow_R_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Holow_R_Frame.setObjectName("Holow_R_Frame")
        self.horizontalLayout_2.addWidget(self.Holow_R_Frame)
        self.verticalLayout.addWidget(self.Bot_Frame)
        self.horizontalLayout.addWidget(self.Right_Frame)
        RegistrationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "MainWindow"))
        self.label_registration.setText(_translate("RegistrationWindow", "Регистрация"))
        self.edit_login_reg.setPlaceholderText(_translate("RegistrationWindow", "Логин"))
        self.edit_password_reg.setPlaceholderText(_translate("RegistrationWindow", "Пароль"))
        self.btn_enter_reg.setText(_translate("RegistrationWindow", "зарегистрироваться"))
